### PR TITLE
User context

### PR DESCRIPTION
**Pull request by angelaleekim**
This PR implements user context for storing user data after login. It enables access to user information for authentication, displays personalized greetings with the user's name, and facilitates calling API endpoints to fetch user tasks based on their ID.

### CODE REVIEW

**Review by emlai1263 — APPROVED** [review]
Looks good :3

**Review by aryaramchander1 — COMMENTED** [review]
Looks great! The only thing I think you can improve on is making sure the number of spaces between blocks of code stays consistent, just so that it looks a little nicer. Other than that, maybe add a few more comments to make the code more readable, but otherwise looks good!

**Comment by angelaleekim** [comment]
> Looks great! The only thing I think you can improve on is making sure the number of spaces between blocks of code stays consistent, just so that it looks a little nicer. Other than that, maybe add a few more comments to make the code more readable, but otherwise looks good!

Sounds good, I'll add for sure add some documentation!

**Review by sab115 — APPROVED** [review]
I think you have clean and concise code with a very consistent format! Good work!

**Comment by sairama02** [comment]
I really like when we had this idea and your implementation of this. The code looks clean and apart from the formatting edits suggested by Arya it all looks good.

**Review by sairama02 — APPROVED** [review]
I really like when we had this idea and your implementation of this. The code looks clean and apart from the formatting edits suggested by Arya it all looks good.

**Comment by angelaleekim** [comment]
Just added commits to include additional documentation and adjusted spacing as per feedback. Thanks, team!

**Review by aryaramchander1 — APPROVED** [review]
Looks good to me!

**Pull request merged**
